# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview.
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Filipe GuimarÃ£es (Forschungszentrum Juelich GmbH)
#    Matthias Lapu (CEA)

# Timezone name (a list can be found in https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
timezone: 'Europe/Berlin'

# Hostname where the LLview website can be accessed (to create links)
# Substitutions can be used with keys given in #(...)#. Inside it:
# - replace can be done with: [string_from,string_to]
# - removals can be done with: (string_to_remove)
# if only jureptool is used and not juri, keep this settings empty
hostname: 'https://llview.fz-juelich.de/#system(-dc)[ ,_]#'
# at the bottom of the generated html page, there will be a logo to llview that
# links to juri, if there is no juri (hostname = ''), put this link instead
standalone_link: 'https://apps.fz-juelich.de/jsc/llview/docu/install/server_install/#jureptool'

# JURI uses Jureptool to create html and pdf reports
# Jureptool relies on plotly and jquery to build the html pages
# The required javascript files for plotly and jquery are located in:
# JURI/js/ext, (https://github.com/FZJ-JSC/JURI/tree/main/js/ext)
# Moreover, Content Delivery Network (CDN) can also be used
# ex :
# plotly_location: 'https://cdn.plot.ly/plotly-3.3.0.min.js'
# jquery_location: 'https://code.jquery.com/jquery-3.6.0.min.js'
# fontawesome_location: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/fontawesome.min.css'

plotly_location: null
jquery_location: null
fontawesome_location: null

#Folder prefix to be added to items in plotlists file
folder_prefix: '$LLVIEW_DATA/$LLVIEW_SYSTEMNAME/tmp/jobreport/data/'

# PDF configuration
page_width: 8.25
page_height: 11.75
max_graph_per_page: 4
max_lines_per_page: 73 # 73 is the maximum number of lines that fit on the page between header and footer

# Timeline configuration
max_timeline_size: 0.87
max_steps_in_timeline: 5000         # Cut steps up to this value
max_timeline_steps_per_page: 128    # Number of max timeline steps per page
min_timeline_steps_last_page: 3     # Min timeline steps in last page (Used when pages>1. Takes priority over the previous one, to avoid having too few steps in a page)
max_bar_size: 0.03                  # Max bar size in gantt charts
max_timeline_height_html: 1000      # Max timeline height in pixels (using by default 3000*barsize for each step)

min_space_for_err: 0.1              # Minimum amount of space left to put error on the same page as timeline

# Font sizes:
hugefont: 11
bigfont: 10
normalfont: 8
smallfont: 7
tinyfont: 6

# Colors:
minmax_color: 'lightblue' # Color for shadowed area between min-max
colors: 'tab10'           # Colors for different interconnect and line plots (when llview_plot_lines is used)
